cf_email = os.environ.get("CF_EMAIL", "example@example.com")
cf_key = os.environ.get("CF_KEY", "")
zone_name = os.environ.get("CF_ZONENAME", "example.com")
domain = os.environ.get("CF_DOMAIN", "www.example.com")
ipv6 = os.environ.get("CF_ENABLE_IPV6", "No")